services:
  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    ports:
      - "3306:3306"

  app:
    build:
      context: ./go-server/
      dockerfile: Dockerfile
    image: app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./.env
